### PR TITLE
 new category and signature updates, Camera category fix

### PR DESCRIPTION
**Pull request by Relkci**
image

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
shoot, sorry, I had merged in signatures and didn't realize this was open, any chance you can pull latest commits and re-submit?

**Comment by Relkci** [comment]
@ChrisTruncer Should be correct now, re-added the new to the bottom of cat & sig files

**Comment by Relkci** [comment]
just bumping for merge -- no conflict and will fix #629

**Comment by ChrisTruncer** [comment]
Thanks for the bump, looks solid. Merging in now.

**Pull request merged**
