### PR TITLE
moved to QT5 and added OSX installer

### PR DESCRIPTION
**Pull request by vyrus001**
osx install script relies on homebrew to install dependancies. All changes testede on OSX 10.12.6

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Awesome,

Thanks for sending this over. I’ll look to get this merged shortly.

**Comment by vyrus001** [comment]
Note, the current version of rdpy is NOT on QT5, however, I have a fork and
subsiquent pull request on that too :)

**Comment by ChrisTruncer** [comment]
Ok,

I’ll check and see if it will work as is. I made a mod to the rdpy library to work for EyeWitness, so I’ll check the status on everything with the changes you submitted.

**Comment by MuhammadKhizerJaved** [comment]
hey can i run Eyewitness on mac? because the setup script giving me error about not supported :/

**Comment by ChrisTruncer** [comment]
Hey, so I am going through this right now an running into an error, specifically with rdpy. You're referencing "from rdpy.ui.qt5 import RDPBitmapToQtImage", but rdpy itself doesn't use qt5. Did you update the rdpy library on your end?

**Comment by DannyCork** [comment]
> hey can i run Eyewitness on mac? because the setup script giving me error about not supported :/

Eyewitness doesn't support Mac Os X.

This patch hasn't been merged and is two years old and untested :(

**Comment by ChrisTruncer** [comment]
It's not merged due to the libraries required for EyeWitness not yet supporting QT5.

**Comment by rhertzog** [comment]
@ChrisTruncer Which libraries are you referring to? Is it only rdpy where @vyrus001 said he had a pending merge request or are there other libraries? @vyrus001 can you point us to that merge request please?

I'm asking because it's really time for eyewitness to switch over. Debian dropped python-qt4 since both Python 2 and Qt4 are dead upstream, so eyewitness is in danger of being removed from Kali as well, for now we have kept the python-qt4 package for the benefit of eyewitness but this can only be a temporary solution. Other packages usually switched to pyside2 that works with Qt5 and with Python 3. We're tracking those issues here in Kali: https://gitlab.com/kalilinux/packages/eyewitness/issues

**Comment by ruevaughn** [comment]
@rhertzog I know this is old, but I'm running into this issue where the bash script won't install on macOS 11.2.3

I believe the Libraries and related info is in his commit he forked. Hope this helps at all?

https://github.com/FortyNorthSecurity/EyeWitness/compare/master...vyrus001:master#diff-0898b9e594967c5383810aa619a1b9fdee37cd7fd72042bff4cc7c67a24bc392R1

**Comment by Relkci** [comment]
hi merge request 
you seem old and conflicted 
may peace find you today

**Pull request closed without merging**
